name: Build

on: [push]

jobs:
  build:

    strategy:
      matrix:
        include:
          - build-name: 'Windows 7'
            python-version: 3.8
            platform: windows-latest
            arch: 'x86'
          - build-name: 'Ubuntu'
            python-version: 3.9
            platform: ubuntu-latest
            arch: 'x64'

    name: ${{ matrix.build-name }}

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.arch }}
    - name: Install dependencies and PyInstaller
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install PyInstaller
    - name: Build
      shell: bash
      run: python -OO build_release.py
    - name: Tar (macOS/Linux)
      if: ${{ runner.os == 'macOS' || runner.os == 'Linux' }}
      run: |
        cd distrib
        tar -czvf ../build-${{ matrix.platform }}.tar.gz ./*
        cd ..
    - name: Upload artifacts (Windows)
      if: ${{ runner.os == 'Windows' }}
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.python-version }}
        path: distrib/*
    - name: Upload artifacts (macOS/Linux)
      if: ${{ runner.os == 'macOS' || runner.os == 'Linux' }}
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.platform }}-${{ matrix.arch }}
        path: build-${{ matrix.platform }}.tar.gz
